import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NavigationMenu } from "@/components/ui/navigation-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="bg-gray-800 text-white p-4">
          <div className="flex justify-between">
            <Link href="/">
              <h1>Job tracker</h1>
            </Link>
            <nav className="flex gap-4">
              <Link href="/" className="hover:underline">
                Dashboard
              </Link>
              <Link href="/add-job" className="hover:underline">
                Add job
              </Link>
              <Link href="/about" className="hover:underline">
                About
              </Link>
            </nav>
          </div>
        </header>
        <main className="flex-1 p-6">{children}</main>
      </body>
    </html>
  );
}
